---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependecies that are no longer needed"
  become: yes
  apt:
    autoremove: yes

- name: "install node"
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create directory"
  become: yes
  file:
    path: ~/web
    state: directory

- name: "Copy index file"
  become: yes
  copy:
    src: index.js
    dest: ~/web/index.js

- name: "Run node app"
  become: yes
  shell: pm2 start ~/web/index.js -f