Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: "TestUdacityKeyPair"
      ImageId: 'ami-0fb1e27304d83032f' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: "t2.micro"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0
Outputs:
  InstanceUrl:
    Description: "Instance Public DNS Name"
    Value:
      Fn::Join: ['', ["http://", Fn::GetAtt: ["Ec2Instance", "PublicDnsName"]]]
