defaults: &defaults
  docker:
    - image: circleci/node
  working_directory: ~/circleci-hello-world

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "Command that prints pipeline ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    working_directory: ~/circleci-hello-world
    steps:
      - checkout
      - run:
          name: Create AWS Infrastructure
          command: >
            aws cloudformation create-stack
            --stack-name "TestCircleCI"
            --template-body file://cloudformation/template.yml
            --region $AWS_DEFAULT_REGION
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    working_directory: ~/circleci-hello-world
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: sudo -H pip install ansible
      - add_ssh_keys:
          fingerprints:
            - "a9:34:93:69:43:66:13:1a:b1:ea:82:9d:92:37:58:bf"
      - run:
          name: Create inventory file
          command: >
            echo "[all]" > .ansible/inventory.txt &&
            aws ec2 describe-instances
              --query 'Reservations[*].Instances[*].PublicIpAddress'
              --output text >> .ansible/inventory.txt
      - run:
          name: Run ansible playbook
          command: ansible-playbook -i .ansible/inventory.txt .ansible/main-remote.yml
  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "Hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - run: echo $OWNER_NAME
      - run: cat ~/output.txt
      - print_pipeline_id
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure
      - configure_infrastructure
