defaults: &defaults
  docker:
    - image: circleci/node
  working_directory: ~/circleci-hello-world

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "Command that prints pipeline ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    working_directory: ~/circleci-hello-world
    steps:
      - checkout
      - run:
          name: Create AWS Infrastructure
          command: >
            aws cloudformation create-stack
            --stack-name "TestCircleCI"
            --template-body cloudformation/template.yml
  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "Hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - run: echo $OWNER_NAME
      - run: cat ~/output.txt
      - print_pipeline_id
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - create_infrastructure
