---
- name: "Ansible Playbook for setting up a remote host"
  hosts: all
  user: ubuntu

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        connect_timeout: 10
        delay: 30
        sleep: 1
        timeout: 600

  roles:
    - setup
